CREATE DATABASE IF NOT EXISTS bon_films;
USE bon_films;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS films (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  genre VARCHAR(100) NOT NULL,
  studio VARCHAR(255) NOT NULL,
  director VARCHAR(255) NOT NULL,
  topBilling VARCHAR(255) NOT NULL,
  synopsis TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  rating INT NOT NULL,
  review TEXT NOT NULL,
  userReviewedId VARCHAR(255) NOT NULL,
  filmId INT NOT NULL,
  dateReviewed DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (filmId) REFERENCES films(id) ON DELETE CASCADE
);
